image: docker:latest

services:
  - docker:dind

before_script:
  - echo ${DOCKER_PASSWORD} | docker login your_registry --username ${DOCKER_USER} --password-stdin

build:
  stage: build
  script: 
    - docker build -t your_registry/mern-starter-auth:latest .
    - docker push your_registry/mern-starter-auth:latest

deploy:
  stage: deploy
  script:
    - microk8s kubectl apply -f mern-starter-auth-depl.yaml
    - microk8s kubectl rollout restart deployment mern-starter-auth-depl
