apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-starter-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-starter-auth
  template:
    metadata:
      labels:
        app: mern-starter-auth
    spec:
      containers:
      - name: mern-starter-auth
        image: registry.jakepeterson.dev/jpeterson/mern-starter-auth/mern-starter-auth:latest
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets-mern-starter-auth
              key: mongodb_conn
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: jwt_secret
        ports:
        - containerPort: 4000
      imagePullSecrets:
        - name: privreg
---
apiVersion: v1
kind: Service
metadata:
  name: mern-starter-auth-srv
spec:
  type: ClusterIP
  selector:
    app: mern-starter-auth
  ports: 
    - name: mern-starter-auth
      protocol: TCP
      # port service is listening on, could be different
      port: 7000
      # the port that the application is listening on, i.e Express Server listening on 4000
      targetPort: 4000
